### ISSUE TITLE
Link, email broken in Kirby 2.5.8

### ISSUE THREAD

**Issue by tristantbg** [medienbaecker/kirby-enhanced-textarea#24]
See : 
https://github.com/getkirby/panel/issues/1121

**Comment by medienbaecker** [comment]
I just pushed version 1.7.2 with the changes for Kirby 2.5.8.
But because of changes like that, I created the SimpleMDE field which is not based on the core textarea field. As the field is very similar and has all of the functionality, I would suggest switching: https://github.com/medienbaecker/kirby-simplemde
